setting1:
  setting1_child: saweet
  deep:
    another: my value
    child:
      value: 2

setting2: 5
setting3: <%= 5 * 5 %>
name: test

language:
  haskell:
    paradigm: functional
  smalltalk:
    paradigm: object oriented 

collides:
  does: not
  
default_settings4:
  haskell:
    paradigm: voodoo
    foo: bar

with_numbers:
  12: 'hello'
  '21': 'bye'
